//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.06 at 10:28:54 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://memorynotfound.com/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.memorynotfound.book;
